### ISSUE TITLE
Failure when working dir has a space in it

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/guide-sessions#76]
Found by @meswan @AustinSeto 

When running the guide in a directory with no space in it, the guide works fine.

When running the guide with the working directory path having a space in the name 
(ex. "/Users/Nimrah.Gill@ibm.com/**Directory Space**/guide-sessions") you get an error when you run `mvn liberty:dev` and the tests fail.

Error:
```
[INFO] [ERROR   ] SESN0307E: An exception occurred when initializing the cache. The exception is: java.lang.IllegalArgumentException: SESN0300E: Invalid syntax in httpSessionCache URI.  Cause is java.net.URISyntaxException: Illegal character in path at index 41: file:/Users/Nimrah.Gill@ibm.com/Directory Space/guide-sessions/finish/target/liberty/wlp/usr/servers/defaultServer/hazelcast-config.xml.
[INFO]  at com.ibm.ws.session.store.cache.CacheStoreService.activateLazily(CacheStoreService.java:184)
[INFO]  at [internal classes]
[INFO]  at com.ibm.ws.session.store.cache.CacheHashMap$$Lambda$130.000000004389E790.run(Unknown Source)
[INFO]  at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
[INFO]  at com.ibm.ws.session.store.cache.CacheHashMap.<init>(CacheHashMap.java:133)
[INFO]  at [internal classes]
[INFO] Caused by: java.net.URISyntaxException: Illegal character in path at index 41: file:/Users/Nimrah.Gill@ibm.com/Directory Space/guide-sessions/finish/target/liberty/wlp/usr/servers/defaultServer/hazelcast-config.xml
[INFO]  at java.base/java.net.URI$Parser.fail(URI.java:2915)
[INFO]  at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
[INFO]  at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3168)
[INFO]  at java.base/java.net.URI$Parser.parse(URI.java:3116)
[INFO]  at java.base/java.net.URI.<init>(URI.java:600)
[INFO]  at com.ibm.ws.session.store.cache.CacheStoreService.activateLazily(CacheStoreService.java:182)
[INFO]  ... 5 more
[INFO] .
[INFO] [ERROR   ] SRVE8059E: An unexpected exception occurred when trying to retrieve the session context
[INFO] Internal Server Error
```

**Comment by gkwan-ibm** [comment]
caused by https://github.com/OpenLiberty/open-liberty/issues/12143
